# Generated by Django 4.2.23 on 2025-07-06 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_text', models.TextField(help_text='Original guideline text')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=10)),
                ('summary', models.TextField(blank=True, help_text='GPT-generated summary', null=True)),
                ('checklist', models.TextField(blank=True, help_text='GPT-generated checklist', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
